### ISSUE TITLE
Error using rlp@2.2.0 as a CLI command 

### ISSUE THREAD

**Issue by tiabc** [ethereumjs/rlp#56]
We used to use `rlp@2.1.0` as a CLI command having installed it with `npm i -g rlp`. Now that we've updated to `rlp@2.2.0`:
```
$ sudo npm i -g rlp
/usr/bin/rlp -> /usr/lib/node_modules/rlp/bin/rlp
/usr/lib
└── rlp@2.2.0
```

we've faced an error:

```
$ rlp encode <whatever>
module.js:549
    throw err;
    ^

Error: Cannot find module './dist/index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/rlp/bin/rlp:3:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

If we `vim /usr/lib/node_modules/rlp/bin/rlp` we'll see that there's `./dist/index.js` included in the beginning which wasn't the case for `rlp@2.1.0`:

```
#!/usr/bin/env node

const rlp = require('./dist/index.js')
const command = process.argv[2]
var raw = process.argv[3]
...
```

I'm submitting this as a bug but maybe I'm supposed to install it differently or something to make it work?

**Comment by holgerd77** [comment]
It's an error on our side - very sorry - we've messed up some path and didn't do a test on the CLI command on release. Will directly prepare a fix and release a version ``v2.3.0`` fixing this.
